<html>
	<head>
		<!-- javascript -->
		<script type="text/javascript" src="../javascript/jquery/jquery-3.2.1.min.js"></script>
		<script type="text/javascript" src="../javascript/jquery/jquery-ui.min.js"></script>
		<script type="text/javascript" src="../javascript/Master.js"></script>
		<!-- css -->
		<link rel="stylesheet" type="text/css" href="../css/reset.css">
		<link rel="stylesheet" type="text/css" href="../css/master.css">
		<link rel="stylesheet" type="text/css" href="../css/contact.css">
	</head>
	<body>
		<div id="mainTitle">
			RNAFamViz
		</div>
		<div class="topnav" id="myTopnav">
			<a href="homePage.phtml">HOME</a>
			<a href="Manual.phtml">MANUAL</a>
			<a href="../../WebApp/html/ApplicationMaster.phtml" target="_blank">SOFTWARE</a>
			<a href="Contact.phtml">ABOUT</a>
  			<a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
		</div>
		<div id="Content">
			<div id="leftContent">
			</div>
			<div id="rightContent">
				<div class="title">
					Supervisors<br>
				</div>
				<div class="names">Aïda Ouangraoua</div>
				<div class="names">Jean-Pierre Sehi Glouzon</div>

				<div class="title">
					Programmers<br>
				</div>
				<div class="names">Alex La Madeleine</div>	
				<div class="names">Guillaume Chaput</div>	
				<div class="names">Rolland jr. Vaillancourt</div>	
					
				<div class="details">
					RNAFamViz is maintained by Jean-Pierre Glouzon<br>
					Suggestions or issues can be reported to <a href="mailto:aida.ouangraoua@usherbrooke.ca">aida.ouangraoua@usherbrooke.ca</a><br>
				</div>

			</div>
		</div>
	</body>
</html>
