<html>
	<head>
		<!-- javascript -->
		<script type="text/javascript" src="../javascript/jquery/jquery-3.2.1.min.js"></script>
		<script type="text/javascript" src="../javascript/jquery/jquery-ui.min.js"></script>
		<script type="text/javascript" src="../javascript/Master.js"></script>
		<!-- css -->
		<link rel="stylesheet" type="text/css" href="../css/reset.css">
		<link rel="stylesheet" type="text/css" href="../css/master.css">
		<link rel="stylesheet" type="text/css" href="../css/manual.css">
	</head>
	<body>
		<div id="mainTitle">
			RNAFamViz
		</div>
		<div class="topnav" id="myTopnav">
			<a href="homePage.phtml">HOME</a>
			<a href="Manual.phtml">MANUAL</a>
			<a href="../../WebApp/html/ApplicationMaster.phtml" target="_blank">SOFTWARE</a>
			<a href="Contact.phtml">ABOUT</a>
  			<a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
		</div>
		<div id="Content">
			<div id="leftContent">
			</div>
			<div id="rightContent">
				<div id="featureTitle">
					RNAFamViz instruction manual (pdf version)
				</div>	
				<div class="manualDownload"> You can download the full manual by clicking <a href="../RNAFamViz_Manuel_Utilisation.pdf" download="RNAFamViz_Manual">Here</a></div>
			</div>
		</div>
	</body>
</html>
